import Head from "next/head";

export default function LayoutApp({ children }) {
  return (
    <div
      style={{
        maxWidth: "1800px",
        width: "100%",
        height: "100%",
        margin: "auto",
      }}
    >
      <Head>
        <title>Pak Group</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pak-toplulugu-logo.png" />
      </Head>
      {children}
    </div>
  );
}
