import { Typography } from "@mui/material";
import Image from "next/image";

const brands = [
  {
    id: 1,
    name: "pak-holding",
    logo: "/home/brands/Pakmaya.png",
    ePosta: "info@pakmaya.com",
    webSitesi: "https://www.pakmaya.com",
    title: "Pak Holding A.Ş.",
    link: "/brands/pak-holding",
    category: "PORTFOY",
    description:
      "1973 yılında Türkiye İzmit’te yaş ekmek mayası üretimine başlayan Pakmaya, modern üretim yöntemleri ve üstün kalitesiyle maya ile özdeş isim olarak tanınıyor. Yatırımları, istikrarlı büyümesi, ürün çeşitlemesi ile bugün 5 kıtada 100 milyonlarca insana lezzet sunan bir dünya markası.",
    bodyImg: "/home/background1.jpg",
    body: [
      "Pakmaya maya fabrikaları",
      "Pakmaya, gelişen ulusal ve uluslararası talebi karşılamak üzere en kaliteli, en titiz, en hijyenik koşullarda üretim ve dağıtım sağlamak için gerekli yatırımları gerçekleştirdi. 1973 yılında Türkiye İzmit –Köseköy’deki ilk maya fabrikası devreye girdi ve maya üretimi başladı.1986’da İzmir – Kemalpaşa, 1990 yılında ise Düzce – Cumayeri tesislerifaaliyete geçti. Pakmaya, 4. maya fabrikasını Romanya’nın Paşcanişehrinde kurdu. Bu modern tesis sadece Romanya’nın maya ihtiyacınınbüyük bölümünü karşılamakla kalmıyor, çevre ülkelere de ihracatgerçekleştiriyor.",
      "Üründe, hizmette öncü",
      "Pakmaya, değirmencilik ve fırıncılık sektörlerine üstün kalite, etkinve verimli hizmet sunuyor, standartları yükseltiyor. Değirmencilikteun geliştirici mikslerin yanı sıra hammadde ve enzimlerle temel birişleve sahip. Fırıncılıkta ise mayalar, ekmek geliştiricileri, ekmek mikslerinin yanı sıra, ekmek yardımcı malzemeleriyle geniş bir ürünyelpazesi sunuyor. Pakmaya Değirmeni projesi ile fırıncıların yanısıra geniş tüketici kitlelere taze, kaliteli, lezzetli çeşit ekmeklersunmak için atılım yapıyor.",
    ],
  },
  {
    id: 2,
    name: "asil-holding",
    logo: "/home/brands/AsGida.png",
    ePosta: "info@pakmaya.com",
    webSitesi: "https://www.pakmaya.com",
    title: "Asil Holding A.Ş.",
    link: "/brands/asil-holding",
    category: "PORTFOY",
    description: "asil holding description",
    bodyImg: "/home/background3.jpg",
    body: ["ASIL HOLDING title", "asil holding body"],
  },
  {
    id: 3,
    name: "pak-gida-uretim-pazarlama",
    logo: "/home/brands/Pakmaya.png",
    ePosta: "info@pakmaya.com",
    webSitesi: "https://www.pakmaya.com",
    title: "Pak Gıda Üretim ve Pazarlama A.Ş.",
    link: "/brands/pak-gida-uretim-pazarlama",
    category: "GIDA",
    description: "pak gida aciklama",
    body: ["pak gida title", "pak gida  body"],
  },
  {
    id: 4,
    name: "as-gida",
    logo: "/home/brands/AsGida.png",
    ePosta: "info@pakmaya.com",
    webSitesi: "https://www.pakmaya.com",
    title: "As Gıda Üretim ve Pazarlama A.Ş.",
    link: "/brands/as-gida",
    category: "GIDA",
    description: " AsGidaaciklama",
    body: ["AsGida title", "AsGida body"],
  },
  {
    id: 5,
    name: "pak-ihracat",
    logo: "/home/brands/PakToplulugu.png",
    ePosta: "info@pakmaya.com",
    webSitesi: "https://www.pakmaya.com",
    title: "Pak İhracat A.Ş.",
    link: "/brands/pak-ihracat",
    category: "GIDA",
    description: "pak ihracat aciklama",
    body: ["pak ihracat title", "Pak ihracat body"],
  },
  {
    id: 6,
    name: "pinat",
    logo: "/home/brands/Pakmaya.png",
    ePosta: "info@pakmaya.com",
    webSitesi: "https://www.pakmaya.com",
    title: "Pinat Gıda Sanayi ve Ticaret A.Ş.",
    link: "/brands/pinat",
    category: "GIDA",
    description: "pinat aciklama",
    body: ["pinat title", "pinat body"],
  },
  {
    id: 7,
    name: "oycan-ithalat",
    logo: "/home/brands/Pakmaya.png",
    ePosta: "info@pakmaya.com",
    webSitesi: "https://www.pakmaya.com",
    title: "Oycan İthalat- İhracat ve Ticaret A.Ş.",
    link: "/brands/oycan-ithalat",
    category: "PORTFOY",
    description: "oycan aciklama",
    body: ["oycan title", "oycan body"],
  },
  {
    id: 8,
    name: "ece",
    logo: "/home/brands/Ece.png",
    ePosta: "info@pakmaya.com",
    webSitesi: "https://www.pakmaya.com",
    title: "Ece Gayrimenkul Yatırım ve Yönetim Hizmetleri A.Ş.",
    link: "/brands/ece",
    category: "EMLAK",
    bodyImg: "/home/background2.jpg",
    description: "ece aciklama",
    body: ["ece title", "ece body"],
  },
  {
    id: 9,
    name: "intermat",
    logo: "/home/brands/Intermat.png",
    ePosta: "info@pakmaya.com",
    webSitesi: "https://www.pakmaya.com",
    title: "İntermat AMBALAJ ve Matbaacılık Sanayi ve Ticaret A.Ş.",
    link: "/brands/intermat",
    category: "AMBALAJ",
    description: "Intermat aciklama",
    body: ["Intermat title", "Intermat body"],
  },
  {
    id: 10,
    name: "integro",
    logo: "/home/brands/Integro.png",
    ePosta: "info@pakmaya.com",
    webSitesi: "https://www.pakmaya.com",
    title: "İntegro Gıda Sanayii ve Ticaret A.Ş.",
    link: "/brands/integro",
    category: "YEM",
    description: "integro aciklama",
    body: ["integro title", "integro body"],
  },
  {
    id: 11,
    name: "kartonsan",
    logo: "/home/brands/Kartonsan.png",
    ePosta: "info@pakmaya.com",
    webSitesi: "https://www.pakmaya.com",
    title: "Kartonsan",
    link: "/brands/kartonsan",
    category: "AMBALAJ",
    description: "kartonsan aciklama",
    body: ["kartonsan title", "kartonsan body"],
  },
  {
    id: 12,
    name: "donkasan",
    logo: "/home/brands/Donkasan.png",
    ePosta: "info@pakmaya.com",
    webSitesi: "https://www.pakmaya.com",
    title: "Dönkasan",
    link: "/brands/donkasan",
    category: "AMBALAJ",
    description: "donkasan aciklama",
    body: ["donkasan title", "donkasan body"],
  },
  {
    id: 13,
    name: "selka",
    logo: "/home/brands/Selka.png",
    ePosta: "info@pakmaya.com",
    webSitesi: "https://www.pakmaya.com",
    title: "Selka",
    link: "/brands/selka",
    category: "AMBALAJ",
    description: "Selka aciklama",
    body: ["Selka title", "Selka body"],
  },
  {
    id: 14,
    name: "rompak",
    logo: "/home/brands/RomPak.png",
    ePosta: "info@pakmaya.com",
    webSitesi: "https://www.pakmaya.com",
    title: "Rompak",
    link: "/brands/rompak",
    category: "GIDA",
    description: " RomPak aciklama",
    body: ["RomPak title", "RomPak body"],
  },
];
export default brands;
